### ISSUE TITLE
idea: filter commits by 'branch depth'

### ISSUE THREAD

**Issue by eins78** [cider-ci/cider-ci_user-interface#12]
'branch depth' = how many children of branch HEAD to show
default: 3-5

example:
- minimal ui (red circle)
- the commits in the big red square would not be show, because the numbers in the small square are larger than 3.

![screen shot 2015-05-07 at 20 13 16](https://cloud.githubusercontent.com/assets/134942/7522693/23623608-f4f7-11e4-9cde-95b03b1a0491.png)

**Comment by DrTom** [comment]
Implemented in 3.4
