### ISSUE TITLE
tree show: missing attachments (caching problem)

### ISSUE THREAD

**Issue by eins78** [cider-ci/cider-ci_user-interface#18]
:warning: **IMPORTANT** :warning: 

Job w/ attachment: https://ci.zhdk.ch/cider-ci/ui/workspace/jobs/17cd003b-5951-41af-b3cc-a5e932992d2e

But this Tree shows no attachments: https://ci.zhdk.ch/cider-ci/ui/workspace/trees/7efe5e9538b68686547aa1b8a9689b3859eadc0f

(via API it does show https://ci.zhdk.ch/cider-ci/api/api-browser/index.html#/cider-ci/api/jobs/17cd003b-5951-41af-b3cc-a5e932992d2e/tree-attachments/)

**Comment by DrTom** [comment]
This works. The link vs no-link can't be easily differentiated with the "cider" color scheme.
